// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA91vD9l6uTWkQwLoRh8gdTm8alc9tckck',
    appId: '1:680638657657:web:5b63139ae91dbcabf050a8',
    messagingSenderId: '680638657657',
    projectId: 'todo-app-a523c',
    authDomain: 'todo-app-a523c.firebaseapp.com',
    storageBucket: 'todo-app-a523c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDc9iWnZET0lj2ZFrY5Ck9JCc3fwqiwh2o',
    appId: '1:680638657657:android:d21d335103e4df01f050a8',
    messagingSenderId: '680638657657',
    projectId: 'todo-app-a523c',
    storageBucket: 'todo-app-a523c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDZ5K-cjHteR56vSlJiOL45vRFBXMYH4k',
    appId: '1:680638657657:ios:9c2bc100f394940bf050a8',
    messagingSenderId: '680638657657',
    projectId: 'todo-app-a523c',
    storageBucket: 'todo-app-a523c.appspot.com',
    iosClientId: '680638657657-v2h4rulrcogrbc3rq13b6n2ammqfh6gh.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDZ5K-cjHteR56vSlJiOL45vRFBXMYH4k',
    appId: '1:680638657657:ios:9c2bc100f394940bf050a8',
    messagingSenderId: '680638657657',
    projectId: 'todo-app-a523c',
    storageBucket: 'todo-app-a523c.appspot.com',
    iosClientId: '680638657657-v2h4rulrcogrbc3rq13b6n2ammqfh6gh.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp',
  );
}
