name: Flutter CI
on: pull_request


jobs:
  build_android:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.5'
          cache: true
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter format --set-exit-if-changed

  build_ios:
    runs-on: macos-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channer: 'stable'
      - run: flutter build ios --no-codesign


