name: Flutter CI
on: pull_request


jobs:
  build_android:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'zulu'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.5'
          cache: true
      - run: flutter pub get
      - run: flutter pub run build_runner build --delete-conflicting-outputs
      - run: flutter build apk
      - run: flutter build appbundle

  build_ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channer: 'stable'
      - run: cd ios && pod install
      - run: flutter pub run build_runner build --delete-conflicting-outputs
      - run: flutter build ios --debug --no-codesign --simulator



